
-- *******************************************************************************************
-- * Date           : 2024-02-12                                                             *
-- * Time           : 09:55                                                                  *
-- * Spreadsheet    : /Users/ifickling/Documents/GitHub/psEnvManager/SpreadSheet/Franco.xlsx *
-- * Environment(s) : PROD_EDW                                                               *
-- *******************************************************************************************


-- +------------------------------------------------------------------------------------------------------+
-- | Create the security roles for DBRV4_SYSADMIN and DBRV4_SECADMIN                                      |
-- +------------------------------------------------------------------------------------------------------+

   USE ROLE USERADMIN;

   CREATE ROLE IF NOT EXISTS DBRV4_SECADMIN;
   CREATE ROLE IF NOT EXISTS DBRV4_SYSADMIN;

   GRANT CREATE ROLE ON ACCOUNT TO DBRV4_SECADMIN;
   GRANT ROLE DBRV4_SECADMIN TO ROLE USERADMIN;
   GRANT ROLE DBRV4_SYSADMIN TO ROLE SYSADMIN;

   USE ROLE SYSADMIN;

   GRANT CREATE DATABASE ON ACCOUNT TO DBRV4_SYSADMIN;
   GRANT CREATE WAREHOUSE ON ACCOUNT TO DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role DBRV4_SYSADMIN                                                                       |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create database DBRV4                                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE DATABASE IF NOT EXISTS DBRV4 DATA_RETENTION_TIME_IN_DAYS = 1;
USE DATABASE DBRV4;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role DBRV4_SECADMIN                                                                       |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Account Level functional roles                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE ROLE IF NOT EXISTS DBRV4_ETL_DEV;
   CREATE ROLE IF NOT EXISTS DBRV4_ANALYST;
   CREATE ROLE IF NOT EXISTS DBRV4_DATA_SCI;
   CREATE ROLE IF NOT EXISTS DBRV4_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Database Level functional roles                                                               |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SYSADMIN;
USE DATABASE DBRV4;
   CREATE DATABASE ROLE IF NOT EXISTS ETL_DEV;
   CREATE DATABASE ROLE IF NOT EXISTS ANALYST;
   CREATE DATABASE ROLE IF NOT EXISTS DATA_SCI;
   CREATE DATABASE ROLE IF NOT EXISTS POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create access roles, Restrictive DB Only Access Roles                                                |
-- +------------------------------------------------------------------------------------------------------+

USE DATABASE DBRV4;
   CREATE DATABASE ROLE IF NOT EXISTS __RAW_RO;
   CREATE DATABASE ROLE IF NOT EXISTS __RAW_SU;
   CREATE DATABASE ROLE IF NOT EXISTS __RAW_RW;
   CREATE DATABASE ROLE IF NOT EXISTS __RAW_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS __EDW_RO;
   CREATE DATABASE ROLE IF NOT EXISTS __EDW_SU;
   CREATE DATABASE ROLE IF NOT EXISTS __EDW_RW;
   CREATE DATABASE ROLE IF NOT EXISTS __EDW_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS __MART_RO;
   CREATE DATABASE ROLE IF NOT EXISTS __MART_SU;
   CREATE DATABASE ROLE IF NOT EXISTS __MART_RW;
   CREATE DATABASE ROLE IF NOT EXISTS __MART_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS __GOVERN_RO;
   CREATE DATABASE ROLE IF NOT EXISTS __GOVERN_SU;
   CREATE DATABASE ROLE IF NOT EXISTS __GOVERN_RW;
   CREATE DATABASE ROLE IF NOT EXISTS __GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the SDR Roles                                                                                 |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SECADMIN;
   CREATE ROLE IF NOT EXISTS _SDR_HIGHLY_CONFIDENTAL;
   CREATE ROLE IF NOT EXISTS _SDR_CONFIDENTIAL;
   CREATE ROLE IF NOT EXISTS _SDR_INTERNAL;
   CREATE ROLE IF NOT EXISTS _SDR_USA;
   CREATE ROLE IF NOT EXISTS _SDR_EMEA;
   CREATE ROLE IF NOT EXISTS _SDR_APAC;
   CREATE ROLE IF NOT EXISTS _SDR_GLOBAL_RESULTS;

-- +------------------------------------------------------------------------------------------------------+
-- | Create warehouse access roles                                                                        |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SECADMIN;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ELT_WH_WU;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ELT_WH_WFULL;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ELT_WH_ALL;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ANALYST_WH_WU;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ANALYST_WH_WFULL;
   CREATE  ROLE IF NOT EXISTS __DBRV4_ANALYST_WH_ALL;
   CREATE  ROLE IF NOT EXISTS __DBRV4_DATA_SCI_WH_WU;
   CREATE  ROLE IF NOT EXISTS __DBRV4_DATA_SCI_WH_WFULL;
   CREATE  ROLE IF NOT EXISTS __DBRV4_DATA_SCI_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on warehouse access roles to DBRV4_SECADMIN                                          |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_ELT_WH_WFULL TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_ELT_WH_ALL TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_ANALYST_WH_WFULL TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_ANALYST_WH_ALL TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_DATA_SCI_WH_WFULL TO ROLE DBRV4_SECADMIN;
   GRANT OWNERSHIP ON ROLE __DBRV4_DATA_SCI_WH_ALL TO ROLE DBRV4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Super-Roles  (ownership stays with USERADMIN)                                                 |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant super-roles to users                                                                           |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role DBRV4_SECADMIN                                                                       |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant account level functional roles to DBRV4_SYSADMIN                                               |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE DBRV4_ETL_DEV TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE DBRV4_ANALYST TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE DBRV4_DATA_SCI TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE DBRV4_POLICY_ADMIN TO ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant database functional roles to DBRV4_SYSADMIN                                                    |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SYSADMIN;
USE DATABASE DBRV4;
   GRANT DATABASE ROLE ETL_DEV TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE ANALYST TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE DATA_SCI TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE POLICY_ADMIN TO ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant database functional roles to account level functional roles                                    |
-- +------------------------------------------------------------------------------------------------------+

   GRANT DATABASE ROLE ETL_DEV TO ROLE DBRV4_ETL_DEV;
   GRANT DATABASE ROLE ANALYST TO ROLE DBRV4_ANALYST;
   GRANT DATABASE ROLE DATA_SCI TO ROLE DBRV4_DATA_SCI;
   GRANT DATABASE ROLE POLICY_ADMIN TO ROLE DBRV4_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to DBRV4_SYSADMIN                                                                 |
-- +------------------------------------------------------------------------------------------------------+

   GRANT DATABASE ROLE __RAW_RO TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __RAW_SU TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __RAW_RW TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __RAW_SFULL TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __EDW_RO TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __EDW_SU TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __EDW_RW TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __EDW_SFULL TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __MART_RO TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __MART_SU TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __MART_RW TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __MART_SFULL TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __GOVERN_RO TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __GOVERN_SU TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __GOVERN_RW TO ROLE DBRV4_SYSADMIN;
   GRANT DATABASE ROLE __GOVERN_SFULL TO ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to functional roles                                                               |
-- +------------------------------------------------------------------------------------------------------+

   GRANT DATABASE ROLE __RAWSFULL TO DATABASE ROLE ETL_DEV;
   GRANT DATABASE ROLE __SFULL TO ROLE RAW_DBRV4_ETL_DEV;
   GRANT DATABASE ROLE __RAWRO TO DATABASE ROLE ANALYST;
   GRANT DATABASE ROLE __RO TO ROLE RAW_DBRV4_ANALYST;
   GRANT DATABASE ROLE __RAWRW TO DATABASE ROLE DATA_SCI;
   GRANT DATABASE ROLE __RW TO ROLE RAW_DBRV4_DATA_SCI;
   GRANT DATABASE ROLE __EDWSFULL TO DATABASE ROLE ETL_DEV;
   GRANT DATABASE ROLE __SFULL TO ROLE EDW_DBRV4_ETL_DEV;
   GRANT DATABASE ROLE __EDWRO TO DATABASE ROLE ANALYST;
   GRANT DATABASE ROLE __RO TO ROLE EDW_DBRV4_ANALYST;
   GRANT DATABASE ROLE __EDWRO TO DATABASE ROLE DATA_SCI;
   GRANT DATABASE ROLE __RO TO ROLE EDW_DBRV4_DATA_SCI;
   GRANT DATABASE ROLE __EDWRO TO DATABASE ROLE POLICY_ADMIN;
   GRANT DATABASE ROLE __RO TO ROLE EDW_DBRV4_POLICY_ADMIN;
   GRANT DATABASE ROLE __MARTSFULL TO DATABASE ROLE ETL_DEV;
   GRANT DATABASE ROLE __SFULL TO ROLE MART_DBRV4_ETL_DEV;
   GRANT DATABASE ROLE __MARTRO TO DATABASE ROLE ANALYST;
   GRANT DATABASE ROLE __RO TO ROLE MART_DBRV4_ANALYST;
   GRANT DATABASE ROLE __MARTRO TO DATABASE ROLE DATA_SCI;
   GRANT DATABASE ROLE __RO TO ROLE MART_DBRV4_DATA_SCI;
   GRANT DATABASE ROLE __MARTRO TO DATABASE ROLE POLICY_ADMIN;
   GRANT DATABASE ROLE __RO TO ROLE MART_DBRV4_POLICY_ADMIN;
   GRANT DATABASE ROLE __GOVERNSFULL TO DATABASE ROLE POLICY_ADMIN;
   GRANT DATABASE ROLE __SFULL TO ROLE GOVERN_DBRV4_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant warehouse access roles to DBRV4_SYSADMIN                                                       |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SECADMIN;
   GRANT ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_ELT_WH_WFULL TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_ELT_WH_ALL TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_ANALYST_WH_WFULL TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_ANALYST_WH_ALL TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WFULL TO ROLE DBRV4_SYSADMIN;
   GRANT ROLE __DBRV4_DATA_SCI_WH_ALL TO ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant virtual warehouse access roles to functional roles                                             |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_ETL_DEV;
   GRANT ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_ANALYST;
   GRANT ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_DATA_SCI;
   GRANT ROLE __DBRV4_ELT_WH_WU TO ROLE DBRV4_POLICY_ADMIN;
   GRANT ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_ETL_DEV;
   GRANT ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_ANALYST;
   GRANT ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_DATA_SCI;
   GRANT ROLE __DBRV4_ANALYST_WH_WU TO ROLE DBRV4_POLICY_ADMIN;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_ETL_DEV;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_ANALYST;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_DATA_SCI;
   GRANT ROLE __DBRV4_DATA_SCI_WH_WU TO ROLE DBRV4_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to super-roles                                                                |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to users                                                                      |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role DBRV4_SYSADMIN                                                                       |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE DBRV4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant db usage to access roles                                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __RAW_SU;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __RAW_SFULL;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __EDW_SU;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __EDW_SFULL;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __MART_SU;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __MART_SFULL;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __GOVERN_SU;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON DATABASE DBRV4 TO DATABASE ROLE __GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the warehouses                                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE WAREHOUSE IF NOT EXISTS DBRV4_ELT_WH WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='xsmall', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=300,auto_resume=true, initially_suspended=true;
   CREATE WAREHOUSE IF NOT EXISTS DBRV4_ANALYST_WH WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='medium', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=300,auto_resume=true, initially_suspended=true;
   CREATE WAREHOUSE IF NOT EXISTS DBRV4_DATA_SCI_WH WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='large', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=300,auto_resume=true, initially_suspended=true;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on warehouses to access roles                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON WAREHOUSE DBRV4_ELT_WH TO ROLE __DBRV4_ELT_WH_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DBRV4_ELT_WH TO ROLE __DBRV4_ELT_WH_WFULL;
   GRANT ALL ON WAREHOUSE DBRV4_ELT_WH TO ROLE __DBRV4_ELT_WH_ALL;
   GRANT USAGE ON WAREHOUSE DBRV4_ANALYST_WH TO ROLE __DBRV4_ANALYST_WH_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DBRV4_ANALYST_WH TO ROLE __DBRV4_ANALYST_WH_WFULL;
   GRANT ALL ON WAREHOUSE DBRV4_ANALYST_WH TO ROLE __DBRV4_ANALYST_WH_ALL;
   GRANT USAGE ON WAREHOUSE DBRV4_DATA_SCI_WH TO ROLE __DBRV4_DATA_SCI_WH_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DBRV4_DATA_SCI_WH TO ROLE __DBRV4_DATA_SCI_WH_WFULL;
   GRANT ALL ON WAREHOUSE DBRV4_DATA_SCI_WH TO ROLE __DBRV4_DATA_SCI_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the schemas                                                                                   |
-- +------------------------------------------------------------------------------------------------------+

   CREATE SCHEMA IF NOT EXISTS DBRV4.RAW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DBRV4.EDW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DBRV4.MART WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DBRV4.GOVERN WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on objects to access roles                                                           |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL REVOKE CURRENT GRANTS;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future ownership on objects to access roles                                                    |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on objects to access roles                                                          |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT USAGE ON SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT USAGE ON SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT USAGE ON SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT USAGE ON SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future privileges on objects to access roles                                                   |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE __RAW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE __EDW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE __MART_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE __GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Build of DBRV4 complete - have a nice day                                                            |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Thanks for using RBAC Automation Manager                                                             |
-- +------------------------------------------------------------------------------------------------------+

