
-- ***********************************************************************************************
-- * Date           : 2023-04-12                                                                 *
-- * Time           : 09:48                                                                      *
-- * Spreadsheet    : /Users/ifickling/Documents/GitHub/psEnvManager/SpreadSheet/RBAC_Demo2.xlsx *
-- * Environment(s) : DEV3                                                                       *
-- ***********************************************************************************************


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create the security roles for DEV3_SYSADMIN and DEV3_USERADMIN                                       ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   USE ROLE USERADMIN;

   CREATE ROLE IF NOT EXISTS DEV3_USERADMIN;
   CREATE ROLE IF NOT EXISTS ;
   CREATE ROLE IF NOT EXISTS DEV3_SYSADMIN;
   CREATE ROLE IF NOT EXISTS ;

   GRANT CREATE ROLE ON ACCOUNT TO DEV3_USERADMIN;
   GRANT ROLE DEV3_USERADMIN TO ROLE USERADMIN;
   GRANT ROLE DEV3_SYSADMIN TO ROLE SYSADMIN;
   GRANT ROLE DEV3_USERADMIN TO ROLE ;
   GRANT ROLE DEV3_SYSADMIN TO ROLE ;

   USE ROLE SYSADMIN;

   GRANT CREATE DATABASE ON ACCOUNT TO DEV3_SYSADMIN;
   GRANT CREATE WAREHOUSE ON ACCOUNT TO DEV3_SYSADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Try to use role USERADMIN                                                                            ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

USE ROLE USERADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create functional roles                                                                              ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE ROLE IF NOT EXISTS DEV3_DEVELOPER;
   CREATE ROLE IF NOT EXISTS DEV3_ETL_PROC;
   CREATE ROLE IF NOT EXISTS DEV3_BI_PROC;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant ownership on functional roles to DEV3_USERADMIN                                                ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT OWNERSHIP ON ROLE DEV3_DEVELOPER TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE DEV3_ETL_PROC TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE DEV3_BI_PROC TO ROLE DEV3_USERADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create access roles, Permissive DB Only Access Roles                                                 ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create access roles, Restrictive DB Only Access Roles                                                ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE ROLE IF NOT EXISTS _DEV3_STA_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_STA_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_STA_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_PSA_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_PSA_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_PSA_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_RSV_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_RSV_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_RSV_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_DWH_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_DWH_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_DWH_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_DMT_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_DMT_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_DMT_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_SFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_TMP_SR;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_TMP_SW;
   CREATE ROLE IF NOT EXISTS _DEV3_TECH_TMP_SFULL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant ownership on schema access roles to DEV3_USERADMIN                                             ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT OWNERSHIP ON ROLE _DEV3_STA_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_STA_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_STA_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_PSA_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_PSA_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_PSA_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_RSV_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_RSV_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_RSV_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DWH_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DWH_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DWH_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DMT_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DMT_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_DMT_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_SFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_TMP_SR TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_TMP_SW TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_TECH_TMP_SFULL TO ROLE DEV3_USERADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create warehouse access roles                                                                        ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE ROLE IF NOT EXISTS _DEV3_WH_ADHOC_WU;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_ADHOC_WFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_ADHOC_ALL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_ETL_WU;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_ETL_WFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_ETL_ALL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_BI_WU;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_BI_WFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_BI_ALL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_LABS_WU;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_LABS_WFULL;
   CREATE ROLE IF NOT EXISTS _DEV3_WH_LABS_ALL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant ownership on warehouse access roles to DEV3_USERADMIN                                          ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT OWNERSHIP ON ROLE _DEV3_WH_ADHOC_WU TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_ADHOC_WFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_ADHOC_ALL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_ETL_WU TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_ETL_WFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_ETL_ALL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_BI_WU TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_BI_WFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_BI_ALL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_LABS_WU TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_LABS_WFULL TO ROLE DEV3_USERADMIN;
   GRANT OWNERSHIP ON ROLE _DEV3_WH_LABS_ALL TO ROLE DEV3_USERADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create Super-Roles  (ownership stays with USERADMIN)                                                 ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE ROLE IF NOT EXISTS SUPER_CONTROL;
   CREATE ROLE IF NOT EXISTS SUPER_ETL;
   CREATE ROLE IF NOT EXISTS SUPER_READER;
   CREATE ROLE IF NOT EXISTS SUPER_WRITER;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant super-roles to users                                                                           ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE SUPER_READER TO USER USER001;
   GRANT ROLE SUPER_READER TO USER USER002;
   GRANT ROLE SUPER_CONTROL TO USER PRD_ADMIN;
   GRANT ROLE SUPER_READER TO USER PRD_ADMIN;
   GRANT ROLE SUPER_WRITER TO USER PRD_ADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Try to use role DEV3_USERADMIN                                                                       ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

USE ROLE DEV3_USERADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant functional roles to DEV3_SYSADMIN                                                              ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE DEV3_DEVELOPER TO ROLE DEV3_SYSADMIN;
   GRANT ROLE DEV3_ETL_PROC TO ROLE DEV3_SYSADMIN;
   GRANT ROLE DEV3_BI_PROC TO ROLE DEV3_SYSADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant access roles to DEV3_SYSADMIN                                                                  ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE _DEV3_STA_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_STA_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_STA_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_PSA_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_PSA_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_PSA_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_RSV_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_RSV_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_RSV_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DWH_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DWH_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DWH_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DMT_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DMT_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_DMT_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_SFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_TMP_SR TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_TMP_SW TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_TECH_TMP_SFULL TO ROLE DEV3_SYSADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant access roles to functional roles                                                               ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE _DEV3_STA_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_STA_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_PSA_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_PSA_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_RSV_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_RSV_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_DWH_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_DWH_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_DMT_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_DMT_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_TECH_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_TECH_SW TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_TECH_TMP_SW TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_TECH_TMP_SW TO ROLE DEV3_ETL_PROC;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant warehouse access roles to DEV3_SYSADMIN                                                        ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE _DEV3_WH_ADHOC_WU TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_ADHOC_WFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_ADHOC_ALL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_ETL_WU TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_ETL_WFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_ETL_ALL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_BI_WU TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_BI_WFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_BI_ALL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_LABS_WU TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_LABS_WFULL TO ROLE DEV3_SYSADMIN;
   GRANT ROLE _DEV3_WH_LABS_ALL TO ROLE DEV3_SYSADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant virtual warehouse access roles to functional roles                                             ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT ROLE _DEV3_WH_ADHOC_WR TO ROLE DEV3_DEVELOPER;
   GRANT ROLE _DEV3_WH_ETL_WR TO ROLE DEV3_ETL_PROC;
   GRANT ROLE _DEV3_WH_BI_WR TO ROLE DEV3_BI_PROC;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant functional roles to super-roles                                                                ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant functional roles to users                                                                      ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Try to use role DEV3_SYSADMIN                                                                        ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

USE ROLE DEV3_SYSADMIN;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create database DEV3                                                                                 ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE DATABASE IF NOT EXISTS DEV3 DATA_RETENTION_TIME_IN_DAYS = 1 DEFAULT_DDL_COLLATION = '''' ;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant db usage to access roles                                                                       ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_STA_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_PSA_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_RSV_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DWH_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_DMT_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_SFULL;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON DATABASE DEV3 TO ROLE _DEV3_TECH_TMP_SFULL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create the warehouses                                                                                ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE WAREHOUSE IF NOT EXISTS DEV3_WH_ADHOC WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='small', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=600,auto_resume=true;
   CREATE WAREHOUSE IF NOT EXISTS DEV3_WH_ETL WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='small', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=600,auto_resume=true;
   CREATE WAREHOUSE IF NOT EXISTS DEV3_WH_BI WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='small', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=600,auto_resume=true;
   CREATE WAREHOUSE IF NOT EXISTS DEV3_WH_LABS WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='small', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=600,auto_resume=true;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant privileges on warehouses to access roles                                                       ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT USAGE ON WAREHOUSE DEV3_WH_ADHOC TO ROLE _DEV3_WH_ADHOC_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DEV3_WH_ADHOC TO ROLE _DEV3_WH_ADHOC_WFULL;
   GRANT ALL ON WAREHOUSE DEV3_WH_ADHOC TO ROLE _DEV3_WH_ADHOC_ALL;
   GRANT USAGE ON WAREHOUSE DEV3_WH_ETL TO ROLE _DEV3_WH_ETL_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DEV3_WH_ETL TO ROLE _DEV3_WH_ETL_WFULL;
   GRANT ALL ON WAREHOUSE DEV3_WH_ETL TO ROLE _DEV3_WH_ETL_ALL;
   GRANT USAGE ON WAREHOUSE DEV3_WH_BI TO ROLE _DEV3_WH_BI_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DEV3_WH_BI TO ROLE _DEV3_WH_BI_WFULL;
   GRANT ALL ON WAREHOUSE DEV3_WH_BI TO ROLE _DEV3_WH_BI_ALL;
   GRANT USAGE ON WAREHOUSE DEV3_WH_LABS TO ROLE _DEV3_WH_LABS_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE DEV3_WH_LABS TO ROLE _DEV3_WH_LABS_WFULL;
   GRANT ALL ON WAREHOUSE DEV3_WH_LABS TO ROLE _DEV3_WH_LABS_ALL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Create the schemas                                                                                   ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   CREATE SCHEMA IF NOT EXISTS DEV3.STA WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.PSA WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.RSV WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.DWH WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.DMT WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.TECH WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS DEV3.TECH_TMP WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant ownership on objects to access roles                                                           ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant future ownership on objects to access roles                                                    ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant privileges on objects to access roles                                                          ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT SELECT ON ALL TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT ON ALL VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT ON ALL STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT ALL ON ALL TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Grant future privileges on objects to access roles                                                   ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

   GRANT SELECT ON FUTURE TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA STA TO ROLE _DEV3_STA_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA PSA TO ROLE _DEV3_PSA_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RSV TO ROLE _DEV3_RSV_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA DWH TO ROLE _DEV3_DWH_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA DMT TO ROLE _DEV3_DMT_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TECH TO ROLE _DEV3_TECH_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SR;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TECH_TMP TO ROLE _DEV3_TECH_TMP_SFULL;

-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Build of DEV3 complete - have a nice day                                                             ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟


-- ▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜
-- ▌ Thanks for using RBAC Automation Manager                                                             ▐
-- ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟

