
-- ***********************************************************************************************************
-- * Date           : 2024-02-22                                                                             *
-- * Time           : 10:31                                                                                  *
-- * Spreadsheet    : /Users/ifickling/Documents/GitHub/psEnvManager/SpreadSheet/EDU_Examples_ArchClass.xlsx *
-- * Environment(s) : PROD_EDW_1                                                                             *
-- ***********************************************************************************************************


-- +------------------------------------------------------------------------------------------------------+
-- | Create the security roles for PROD_EDW4_SYSADMIN and PROD_EDW4_SECADMIN                              |
-- +------------------------------------------------------------------------------------------------------+

   USE ROLE USERADMIN;

   CREATE ROLE IF NOT EXISTS PROD_EDW4_SECADMIN;
   CREATE ROLE IF NOT EXISTS PROD_EDW4_SYSADMIN;

   GRANT CREATE ROLE ON ACCOUNT TO PROD_EDW4_SECADMIN;
   GRANT ROLE PROD_EDW4_SECADMIN TO ROLE USERADMIN;
   GRANT ROLE PROD_EDW4_SYSADMIN TO ROLE SYSADMIN;

   USE ROLE SYSADMIN;

   GRANT CREATE DATABASE ON ACCOUNT TO PROD_EDW4_SYSADMIN;
   GRANT CREATE WAREHOUSE ON ACCOUNT TO PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role PROD_EDW4_SYSADMIN                                                                   |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create database PROD_EDW4                                                                            |
-- +------------------------------------------------------------------------------------------------------+

   CREATE DATABASE IF NOT EXISTS PROD_EDW4 DATA_RETENTION_TIME_IN_DAYS = 1;
USE DATABASE PROD_EDW4;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role PROD_EDW4_SECADMIN                                                                   |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Account Level functional roles                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE ROLE IF NOT EXISTS PROD_EDW4_ELT_DEV;
   CREATE ROLE IF NOT EXISTS PROD_EDW4_MYROLE;
   CREATE ROLE IF NOT EXISTS PROD_EDW4_ANALYST;
   CREATE ROLE IF NOT EXISTS PROD_EDW4_DATA_SCI;

-- +------------------------------------------------------------------------------------------------------+
-- | Create access roles, Restrictive DB Only Access Roles                                                |
-- +------------------------------------------------------------------------------------------------------+

USE DATABASE PROD_EDW4;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_RAW_RO;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_RAW_SU;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_RAW_RW;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_RAW_SFULL;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_EDW_RO;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_EDW_SU;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_EDW_RW;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_EDW_SFULL;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_MART_RO;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_MART_SU;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_MART_RW;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_MART_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the SDR Roles                                                                                 |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SECADMIN;
   CREATE ROLE IF NOT EXISTS _SDR_HIGHLY_CONFIDENTAL;
   CREATE ROLE IF NOT EXISTS _SDR_CONFIDENTIAL;
   CREATE ROLE IF NOT EXISTS _SDR_AFRICA;
   CREATE ROLE IF NOT EXISTS _SDR_ASIA;
   CREATE ROLE IF NOT EXISTS _SDR_EUROPE;
   CREATE ROLE IF NOT EXISTS _SDR_MIDDLE_EAST;
   CREATE ROLE IF NOT EXISTS _SDR_ALL_REGIONS;

-- +------------------------------------------------------------------------------------------------------+
-- | Create warehouse access roles                                                                        |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SECADMIN;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_ADHOC_WH_WU;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_ADHOC_WH_WFULL;
   CREATE  ROLE IF NOT EXISTS _PROD_EDW4_ADHOC_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on warehouse access roles to PROD_EDW4_SECADMIN                                      |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_SECADMIN;
   GRANT OWNERSHIP ON ROLE _PROD_EDW4_ADHOC_WH_WFULL TO ROLE PROD_EDW4_SECADMIN;
   GRANT OWNERSHIP ON ROLE _PROD_EDW4_ADHOC_WH_ALL TO ROLE PROD_EDW4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Super-Roles  (ownership stays with USERADMIN)                                                 |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant super-roles to users                                                                           |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role PROD_EDW4_SECADMIN                                                                   |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant account level functional roles to PROD_EDW4_SYSADMIN                                           |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE PROD_EDW4_ELT_DEV TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE PROD_EDW4_MYROLE TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE PROD_EDW4_ANALYST TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE PROD_EDW4_DATA_SCI TO ROLE PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to PROD_EDW4_SYSADMIN                                                             |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE _PROD_EDW4_RAW_RO TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_RAW_SU TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_RAW_RW TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_RAW_SFULL TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_EDW_RO TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_EDW_SU TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_EDW_RW TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_EDW_SFULL TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_MART_RO TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_MART_SU TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_MART_RW TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_MART_SFULL TO ROLE PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to functional roles                                                               |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE _PROD_EDW4_RAW_SFULL TO ROLE PROD_EDW4_ELT_DEV;
   GRANT ROLE _PROD_EDW4_RAW_SFULL TO ROLE PROD_EDW4_MYROLE;
   GRANT ROLE _PROD_EDW4_RAW_RO TO ROLE PROD_EDW4_ANALYST;
   GRANT ROLE _PROD_EDW4_RAW_RW TO ROLE PROD_EDW4_DATA_SCI;
   GRANT ROLE _PROD_EDW4_EDW_SFULL TO ROLE PROD_EDW4_ELT_DEV;
   GRANT ROLE _PROD_EDW4_EDW_SFULL TO ROLE PROD_EDW4_MYROLE;
   GRANT ROLE _PROD_EDW4_EDW_RO TO ROLE PROD_EDW4_ANALYST;
   GRANT ROLE _PROD_EDW4_EDW_RO TO ROLE PROD_EDW4_DATA_SCI;
   GRANT ROLE _PROD_EDW4_MART_SFULL TO ROLE PROD_EDW4_ELT_DEV;
   GRANT ROLE _PROD_EDW4_MART_SFULL TO ROLE PROD_EDW4_MYROLE;
   GRANT ROLE _PROD_EDW4_MART_RO TO ROLE PROD_EDW4_ANALYST;
   GRANT ROLE _PROD_EDW4_MART_RO TO ROLE PROD_EDW4_DATA_SCI;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant warehouse access roles to PROD_EDW4_SYSADMIN                                                   |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SECADMIN;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_WFULL TO ROLE PROD_EDW4_SYSADMIN;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_ALL TO ROLE PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant virtual warehouse access roles to functional roles                                             |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_ELT_DEV;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_MYROLE;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_ANALYST;
   GRANT ROLE _PROD_EDW4_ADHOC_WH_WU TO ROLE PROD_EDW4_DATA_SCI;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to super-roles                                                                |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to users                                                                      |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role PROD_EDW4_SYSADMIN                                                                   |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE PROD_EDW4_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant db usage to access roles                                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_RAW_SU;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_EDW_SU;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_MART_SU;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON DATABASE PROD_EDW4 TO ROLE _PROD_EDW4_MART_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the warehouses                                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE WAREHOUSE IF NOT EXISTS PROD_EDW4_ADHOC_WH WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='xsmall', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=300,auto_resume=true, initially_suspended=true;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on warehouses to access roles                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON WAREHOUSE PROD_EDW4_ADHOC_WH TO ROLE _PROD_EDW4_ADHOC_WH_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE PROD_EDW4_ADHOC_WH TO ROLE _PROD_EDW4_ADHOC_WH_WFULL;
   GRANT ALL ON WAREHOUSE PROD_EDW4_ADHOC_WH TO ROLE _PROD_EDW4_ADHOC_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the schemas                                                                                   |
-- +------------------------------------------------------------------------------------------------------+

   CREATE SCHEMA IF NOT EXISTS PROD_EDW4.RAW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS PROD_EDW4.EDW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS PROD_EDW4.MART WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on objects to access roles                                                           |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL REVOKE CURRENT GRANTS;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future ownership on objects to access roles                                                    |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on objects to access roles                                                          |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT USAGE ON SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT USAGE ON SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT USAGE ON SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future privileges on objects to access roles                                                   |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO ROLE _PROD_EDW4_RAW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO ROLE _PROD_EDW4_EDW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SU;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO ROLE _PROD_EDW4_MART_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Build of PROD_EDW4 complete - have a nice day                                                        |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Thanks for using RBAC Automation Manager                                                             |
-- +------------------------------------------------------------------------------------------------------+

