
-- ***********************************************************************************************************
-- * Date           : 2024-06-07                                                                             *
-- * Time           : 09:54                                                                                  *
-- * Spreadsheet    : /Users/ifickling/Documents/GitHub/psEnvManager/SpreadSheet/EDU_Examples_ArchClass.xlsx *
-- * Environment(s) : PROD_EDW_1_Goverance                                                                   *
-- ***********************************************************************************************************


-- +------------------------------------------------------------------------------------------------------+
-- | Create the security roles for INSTRUCTOR1_GOVDB_SYSADMIN and INSTRUCTOR1_GOVDB_SECADMIN              |
-- +------------------------------------------------------------------------------------------------------+

   USE ROLE USERADMIN;

   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_SECADMIN;
   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_SYSADMIN;

   GRANT CREATE ROLE ON ACCOUNT TO INSTRUCTOR1_GOVDB_SECADMIN;
   GRANT ROLE INSTRUCTOR1_GOVDB_SECADMIN TO ROLE USERADMIN;
   GRANT ROLE INSTRUCTOR1_GOVDB_SYSADMIN TO ROLE SYSADMIN;

   USE ROLE SYSADMIN;

   GRANT CREATE DATABASE ON ACCOUNT TO INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT CREATE WAREHOUSE ON ACCOUNT TO INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role INSTRUCTOR1_GOVDB_SYSADMIN                                                           |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create database INSTRUCTOR1_GOVDB                                                                    |
-- +------------------------------------------------------------------------------------------------------+

   CREATE DATABASE IF NOT EXISTS INSTRUCTOR1_GOVDB DATA_RETENTION_TIME_IN_DAYS = 1;
USE DATABASE INSTRUCTOR1_GOVDB;

-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role INSTRUCTOR1_GOVDB_SECADMIN                                                           |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Account Level functional roles                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_ETL_DEV;
   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_ANALYST;
   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_DATA_SCI;
   CREATE ROLE IF NOT EXISTS INSTRUCTOR1_GOVDB_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create access roles, Restrictive DB Only Access Roles                                                |
-- +------------------------------------------------------------------------------------------------------+

USE DATABASE INSTRUCTOR1_GOVDB;
   CREATE DATABASE ROLE IF NOT EXISTS _RAW_RO;
   CREATE DATABASE ROLE IF NOT EXISTS _RAW_RW;
   CREATE DATABASE ROLE IF NOT EXISTS _RAW_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS _EDW_RO;
   CREATE DATABASE ROLE IF NOT EXISTS _EDW_RW;
   CREATE DATABASE ROLE IF NOT EXISTS _EDW_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS _MART_RO;
   CREATE DATABASE ROLE IF NOT EXISTS _MART_RW;
   CREATE DATABASE ROLE IF NOT EXISTS _MART_SFULL;
   CREATE DATABASE ROLE IF NOT EXISTS _GOVERN_RO;
   CREATE DATABASE ROLE IF NOT EXISTS _GOVERN_RW;
   CREATE DATABASE ROLE IF NOT EXISTS _GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the SDR Roles                                                                                 |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SECADMIN;
   CREATE ROLE IF NOT EXISTS _SDR_HIGHLY_CONFIDENTAL;
   CREATE ROLE IF NOT EXISTS _SDR_CONFIDENTIAL;
   CREATE ROLE IF NOT EXISTS _SDR_AFRICA;
   CREATE ROLE IF NOT EXISTS _SDR_ASIA;
   CREATE ROLE IF NOT EXISTS _SDR_EUROPE;
   CREATE ROLE IF NOT EXISTS _SDR_MIDDLE_EAST;
   CREATE ROLE IF NOT EXISTS _SDR_ALL_REGIONS;

-- +------------------------------------------------------------------------------------------------------+
-- | Create warehouse access roles                                                                        |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SECADMIN;
   CREATE  ROLE IF NOT EXISTS _INSTRUCTOR1_GOVDB_ADHOC_WH_WU;
   CREATE  ROLE IF NOT EXISTS _INSTRUCTOR1_GOVDB_ADHOC_WH_WFULL;
   CREATE  ROLE IF NOT EXISTS _INSTRUCTOR1_GOVDB_ADHOC_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on warehouse access roles to INSTRUCTOR1_GOVDB_SECADMIN                              |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_SECADMIN;
   GRANT OWNERSHIP ON ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WFULL TO ROLE INSTRUCTOR1_GOVDB_SECADMIN;
   GRANT OWNERSHIP ON ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_ALL TO ROLE INSTRUCTOR1_GOVDB_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Create Super-Roles  (ownership stays with USERADMIN)                                                 |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant super-roles to users                                                                           |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role INSTRUCTOR1_GOVDB_SECADMIN                                                           |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SECADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant account level functional roles to INSTRUCTOR1_GOVDB_SYSADMIN                                   |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE INSTRUCTOR1_GOVDB_ETL_DEV TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT ROLE INSTRUCTOR1_GOVDB_ANALYST TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT ROLE INSTRUCTOR1_GOVDB_DATA_SCI TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT ROLE INSTRUCTOR1_GOVDB_POLICY_ADMIN TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to INSTRUCTOR1_GOVDB_SYSADMIN                                                     |
-- +------------------------------------------------------------------------------------------------------+

   GRANT DATABASE ROLE _RAW_RO TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _RAW_RW TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _RAW_SFULL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _EDW_RO TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _EDW_RW TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _EDW_SFULL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _MART_RO TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _MART_RW TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _MART_SFULL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _GOVERN_RO TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _GOVERN_RW TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT DATABASE ROLE _GOVERN_SFULL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant access roles to functional roles                                                               |
-- +------------------------------------------------------------------------------------------------------+

   GRANT DATABASE ROLE _RAW_SFULL to role INSTRUCTOR1_GOVDB_ETL_DEV;
   GRANT DATABASE ROLE _RAW_RO to role INSTRUCTOR1_GOVDB_ANALYST;
   GRANT DATABASE ROLE _RAW_RW to role INSTRUCTOR1_GOVDB_DATA_SCI;
   GRANT DATABASE ROLE _RAW_RO to role INSTRUCTOR1_GOVDB_POLICY_ADMIN;
   GRANT DATABASE ROLE _EDW_SFULL to role INSTRUCTOR1_GOVDB_ETL_DEV;
   GRANT DATABASE ROLE _EDW_RO to role INSTRUCTOR1_GOVDB_ANALYST;
   GRANT DATABASE ROLE _EDW_RO to role INSTRUCTOR1_GOVDB_DATA_SCI;
   GRANT DATABASE ROLE _EDW_RO to role INSTRUCTOR1_GOVDB_POLICY_ADMIN;
   GRANT DATABASE ROLE _MART_SFULL to role INSTRUCTOR1_GOVDB_ETL_DEV;
   GRANT DATABASE ROLE _MART_RO to role INSTRUCTOR1_GOVDB_ANALYST;
   GRANT DATABASE ROLE _MART_RO to role INSTRUCTOR1_GOVDB_DATA_SCI;
   GRANT DATABASE ROLE _MART_RO to role INSTRUCTOR1_GOVDB_POLICY_ADMIN;
   GRANT DATABASE ROLE _GOVERN_SFULL to role INSTRUCTOR1_GOVDB_ETL_DEV;
   GRANT DATABASE ROLE _GOVERN_RO to role INSTRUCTOR1_GOVDB_ANALYST;
   GRANT DATABASE ROLE _GOVERN_RO to role INSTRUCTOR1_GOVDB_DATA_SCI;
   GRANT DATABASE ROLE _GOVERN_RW to role INSTRUCTOR1_GOVDB_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant warehouse access roles to INSTRUCTOR1_GOVDB_SYSADMIN                                           |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SECADMIN;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WFULL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_ALL TO ROLE INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant virtual warehouse access roles to functional roles                                             |
-- +------------------------------------------------------------------------------------------------------+

   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_ETL_DEV;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_ANALYST;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_DATA_SCI;
   GRANT ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU TO ROLE INSTRUCTOR1_GOVDB_POLICY_ADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to super-roles                                                                |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Grant functional roles to users                                                                      |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | |||||||||||||||||||||||||||||||||||||||||| Switch role... |||||||||||||||||||||||||||||||||||||||||| |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Try to use role INSTRUCTOR1_GOVDB_SYSADMIN                                                           |
-- +------------------------------------------------------------------------------------------------------+

USE ROLE INSTRUCTOR1_GOVDB_SYSADMIN;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant db usage to access roles                                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _RAW_SFULL;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _EDW_SFULL;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _MART_SFULL;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON DATABASE INSTRUCTOR1_GOVDB TO DATABASE ROLE _GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the warehouses                                                                                |
-- +------------------------------------------------------------------------------------------------------+

   CREATE WAREHOUSE IF NOT EXISTS INSTRUCTOR1_GOVDB_ADHOC_WH WITH WAREHOUSE_TYPE = 'STANDARD' warehouse_size='xsmall', scaling_policy='standard',min_cluster_count=1, max_cluster_count=1, auto_suspend=300,auto_resume=true, initially_suspended=true;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on warehouses to access roles                                                       |
-- +------------------------------------------------------------------------------------------------------+

   GRANT USAGE ON WAREHOUSE INSTRUCTOR1_GOVDB_ADHOC_WH TO ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WU;
   GRANT USAGE, OPERATE,MODIFY ON WAREHOUSE INSTRUCTOR1_GOVDB_ADHOC_WH TO ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_WFULL;
   GRANT ALL ON WAREHOUSE INSTRUCTOR1_GOVDB_ADHOC_WH TO ROLE _INSTRUCTOR1_GOVDB_ADHOC_WH_ALL;

-- +------------------------------------------------------------------------------------------------------+
-- | Create the schemas                                                                                   |
-- +------------------------------------------------------------------------------------------------------+

   CREATE SCHEMA IF NOT EXISTS INSTRUCTOR1_GOVDB.RAW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS INSTRUCTOR1_GOVDB.EDW WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS INSTRUCTOR1_GOVDB.MART WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';
   CREATE SCHEMA IF NOT EXISTS INSTRUCTOR1_GOVDB.GOVERN WITH MANAGED ACCESS data_retention_time_in_days=1 comment = '';

-- +------------------------------------------------------------------------------------------------------+
-- | Grant ownership on objects to access roles                                                           |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;
   GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL REVOKE CURRENT GRANTS;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future ownership on objects to access roles                                                    |
-- +------------------------------------------------------------------------------------------------------+

   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant privileges on objects to access roles                                                          |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT SELECT ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE,READ ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT SELECT ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT ALL ON ALL TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON ALL PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Grant future privileges on objects to access roles                                                   |
-- +------------------------------------------------------------------------------------------------------+

   GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA RAW TO DATABASE ROLE _RAW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EDW TO DATABASE ROLE _EDW_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MART TO DATABASE ROLE _MART_SFULL;
   GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE,READ ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RO;
   GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT SELECT ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_RW;
   GRANT ALL ON FUTURE TABLES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE VIEWS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE STAGES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE STREAMS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE SEQUENCES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;
   GRANT ALL ON FUTURE PROCEDURES IN SCHEMA GOVERN TO DATABASE ROLE _GOVERN_SFULL;

-- +------------------------------------------------------------------------------------------------------+
-- | Build of INSTRUCTOR1_GOVDB complete - have a nice day                                                |
-- +------------------------------------------------------------------------------------------------------+


-- +------------------------------------------------------------------------------------------------------+
-- | Thanks for using RBAC Automation Manager                                                             |
-- +------------------------------------------------------------------------------------------------------+

